//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "CQ_NETMF_CQ_FRK_FM3_Hardware.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_CQ_NETMF_CQ_FRK_FM3_Hardware_CQ_NETMF_CQ_FRK_FM3_Hardware_FM3_I2CDevice::I2CDevice_SetChannel___STATIC__VOID__U4,
    NULL,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_CQ_NETMF_CQ_FRK_FM3_Hardware =
{
    "CQ_NETMF_CQ_FRK_FM3_Hardware", 
    0xC1FE27AC,
    method_lookup
};

