//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "CQ_NETMF_MP3.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    Library_CQ_NETMF_MP3_CQ_NETMF_MP3_MP3Device::MP3Device_MP3_Initialize___STATIC__VOID,
    Library_CQ_NETMF_MP3_CQ_NETMF_MP3_MP3Device::MP3Device_MP3_Play___STATIC__VOID__STRING,
    Library_CQ_NETMF_MP3_CQ_NETMF_MP3_MP3Device::MP3Device_MP3_Stop___STATIC__VOID__STRING,
    Library_CQ_NETMF_MP3_CQ_NETMF_MP3_MP3Device::MP3Device_MP3_Pause___STATIC__VOID__STRING,
    Library_CQ_NETMF_MP3_CQ_NETMF_MP3_MP3Device::MP3Device_MP3_Uninitialize___STATIC__VOID,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_CQ_NETMF_MP3 =
{
    "CQ_NETMF_MP3", 
    0xD590B569,
    method_lookup
};

