//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "RawIO.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    Library_RawIO_Microsoft_SPOT_Hardware_AddressSpace::_ctor___VOID__STRING__I4,
    Library_RawIO_Microsoft_SPOT_Hardware_AddressSpace::get_BitWdith___I4,
    Library_RawIO_Microsoft_SPOT_Hardware_AddressSpace::get_Length___U4,
    NULL,
    Library_RawIO_Microsoft_SPOT_Hardware_AddressSpaceUInt16::get_Item___U2__U4,
    Library_RawIO_Microsoft_SPOT_Hardware_AddressSpaceUInt16::set_Item___VOID__U4__U2,
    NULL,
    Library_RawIO_Microsoft_SPOT_Hardware_AddressSpaceUInt32::get_Item___U4__U4,
    Library_RawIO_Microsoft_SPOT_Hardware_AddressSpaceUInt32::set_Item___VOID__U4__U4,
    NULL,
    Library_RawIO_Microsoft_SPOT_Hardware_AddressSpaceUInt8::get_Item___U1__U4,
    Library_RawIO_Microsoft_SPOT_Hardware_AddressSpaceUInt8::set_Item___VOID__U4__U1,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Microsoft_SPOT_HAL =
{
    "Microsoft_SPOT_HAL", 
    0x5DAE3344,
    method_lookup
};

