//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _RAWIO_H_
#define _RAWIO_H_

#include <TinyCLR_Interop.h>
struct Library_RawIO_Microsoft_SPOT_Hardware_AddressSpace
{
    static const int FIELD__ASID = 1;

    TINYCLR_NATIVE_DECLARE(_ctor___VOID__STRING__I4);
    TINYCLR_NATIVE_DECLARE(get_BitWdith___I4);
    TINYCLR_NATIVE_DECLARE(get_Length___U4);

    //--//

};

struct Library_RawIO_Microsoft_SPOT_Hardware_AddressSpaceUInt16
{
    TINYCLR_NATIVE_DECLARE(get_Item___U2__U4);
    TINYCLR_NATIVE_DECLARE(set_Item___VOID__U4__U2);

    //--//

};

struct Library_RawIO_Microsoft_SPOT_Hardware_AddressSpaceUInt32
{
    TINYCLR_NATIVE_DECLARE(get_Item___U4__U4);
    TINYCLR_NATIVE_DECLARE(set_Item___VOID__U4__U4);

    //--//

};

struct Library_RawIO_Microsoft_SPOT_Hardware_AddressSpaceUInt8
{
    TINYCLR_NATIVE_DECLARE(get_Item___U1__U4);
    TINYCLR_NATIVE_DECLARE(set_Item___VOID__U4__U1);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Microsoft_SPOT_HAL;

#endif  //_RAWIO_H_
