//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "CQ_NETMF_LCD.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    Library_CQ_NETMF_LCD_CQ_NETMF_LCD_LCDDevice::LCDDevice_LCD_Initialize___STATIC__VOID,
    Library_CQ_NETMF_LCD_CQ_NETMF_LCD_LCDDevice::LCDDevice_LCD_Clear___STATIC__VOID,
    Library_CQ_NETMF_LCD_CQ_NETMF_LCD_LCDDevice::LCDDevice_LCD_BitBltEx___STATIC__VOID__U4__U4__U4__U4__SZARRAY_U1,
    Library_CQ_NETMF_LCD_CQ_NETMF_LCD_LCDDevice::LCDDevice_LCD_WriteFormattedChar___STATIC__VOID__U2,
    NULL,
    NULL,
    NULL,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_CQ_NETMF_LCD =
{
    "CQ_NETMF_LCD", 
    0xD6798F1F,
    method_lookup
};

