//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "CQ_NETMF_SD.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    Library_CQ_NETMF_SD_CQ_NETMF_SD_StorageDevice::SDSPI_Mount___STATIC__VOID__STRING__U4__U4__U4,
    Library_CQ_NETMF_SD_CQ_NETMF_SD_StorageDevice::SDSPI_Unmount___STATIC__VOID,
    NULL,
    NULL,
    NULL,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_CQ_NETMF_SD =
{
    "CQ_NETMF_SD", 
    0xF9AC26E5,
    method_lookup
};

