//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _CQ_NETMF_CQ_FRK_FM3_HARDWARE_H_
#define _CQ_NETMF_CQ_FRK_FM3_HARDWARE_H_

#include <TinyCLR_Interop.h>
struct Library_CQ_NETMF_CQ_FRK_FM3_Hardware_CQ_NETMF_CQ_FRK_FM3_Hardware_FM3_I2CDevice
{
    static const int FIELD__fm3_i2c = 4;
    static const int FIELD__fm3_i2c_ch = 5;

    TINYCLR_NATIVE_DECLARE(I2CDevice_SetChannel___STATIC__VOID__U4);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_CQ_NETMF_CQ_FRK_FM3_Hardware;

#endif  //_CQ_NETMF_CQ_FRK_FM3_HARDWARE_H_
