//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "CQ_NETMF_CQ_FRK_FM3_Hardware.h"
#include "CQ_NETMF_CQ_FRK_FM3_Hardware_CQ_NETMF_CQ_FRK_FM3_Hardware_FM3_I2CDevice.h"

using namespace CQ::NETMF::CQ_FRK_FM3::Hardware;


HRESULT Library_CQ_NETMF_CQ_FRK_FM3_Hardware_CQ_NETMF_CQ_FRK_FM3_Hardware_FM3_I2CDevice::I2CDevice_SetChannel___STATIC__VOID__U4( CLR_RT_StackFrame& stack )
{
    TINYCLR_HEADER(); hr = S_OK;
    {
        UINT32 param0;
        TINYCLR_CHECK_HRESULT( Interop_Marshal_UINT32( stack, 0, param0 ) );

        FM3_I2CDevice::I2CDevice_SetChannel( param0, hr );
        TINYCLR_CHECK_HRESULT( hr );
    }
    TINYCLR_NOCLEANUP();
}
