//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _CQ_NETMF_LEDMATRIX_H_
#define _CQ_NETMF_LEDMATRIX_H_

#include <TinyCLR_Interop.h>
struct Library_CQ_NETMF_LEDMATRIX_CQ_NETMF_LEDMATRIX_RGBLEDMatrix
{
    TINYCLR_NATIVE_DECLARE(RGBLEDMatrix_Initialize___STATIC__VOID__SZARRAY_U4);
    TINYCLR_NATIVE_DECLARE(RGBLEDMatrix_SelectLine___STATIC__VOID__U1);
    TINYCLR_NATIVE_DECLARE(RGBLEDMatrix_TurnOn___STATIC__VOID);
    TINYCLR_NATIVE_DECLARE(RGBLEDMatrix_TurnOff___STATIC__VOID);
    TINYCLR_NATIVE_DECLARE(RGBLEDMatrix_DrawLine8___STATIC__VOID__U1__U1__U1);
    TINYCLR_NATIVE_DECLARE(RGBLEDMatrix_DrawLine64___STATIC__VOID__U1__U1__U1);
    TINYCLR_NATIVE_DECLARE(RGBLEDMatrix_DrawPat___STATIC__VOID__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(RGBLEDMatrix_DrawFont8x8___STATIC__VOID__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(RGBLEDMatrix_GetFontBitmap___STATIC__VOID__U2__SZARRAY_U1);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_CQ_NETMF_LEDMATRIX;

#endif  //_CQ_NETMF_LEDMATRIX_H_
