//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "CQ_NETMF_LEDMATRIX.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_CQ_NETMF_LEDMATRIX_CQ_NETMF_LEDMATRIX_RGBLEDMatrix::RGBLEDMatrix_Initialize___STATIC__VOID__SZARRAY_U4,
    Library_CQ_NETMF_LEDMATRIX_CQ_NETMF_LEDMATRIX_RGBLEDMatrix::RGBLEDMatrix_SelectLine___STATIC__VOID__U1,
    Library_CQ_NETMF_LEDMATRIX_CQ_NETMF_LEDMATRIX_RGBLEDMatrix::RGBLEDMatrix_TurnOn___STATIC__VOID,
    Library_CQ_NETMF_LEDMATRIX_CQ_NETMF_LEDMATRIX_RGBLEDMatrix::RGBLEDMatrix_TurnOff___STATIC__VOID,
    Library_CQ_NETMF_LEDMATRIX_CQ_NETMF_LEDMATRIX_RGBLEDMatrix::RGBLEDMatrix_DrawLine8___STATIC__VOID__U1__U1__U1,
    Library_CQ_NETMF_LEDMATRIX_CQ_NETMF_LEDMATRIX_RGBLEDMatrix::RGBLEDMatrix_DrawLine64___STATIC__VOID__U1__U1__U1,
    Library_CQ_NETMF_LEDMATRIX_CQ_NETMF_LEDMATRIX_RGBLEDMatrix::RGBLEDMatrix_DrawPat___STATIC__VOID__SZARRAY_U1,
    Library_CQ_NETMF_LEDMATRIX_CQ_NETMF_LEDMATRIX_RGBLEDMatrix::RGBLEDMatrix_DrawFont8x8___STATIC__VOID__SZARRAY_U1,
    Library_CQ_NETMF_LEDMATRIX_CQ_NETMF_LEDMATRIX_RGBLEDMatrix::RGBLEDMatrix_GetFontBitmap___STATIC__VOID__U2__SZARRAY_U1,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_CQ_NETMF_LEDMATRIX =
{
    "CQ_NETMF_LEDMATRIX", 
    0xD4D9C266,
    method_lookup
};

