//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _CQ_NETMF_MP3_H_
#define _CQ_NETMF_MP3_H_

#include <TinyCLR_Interop.h>
struct Library_CQ_NETMF_MP3_CQ_NETMF_MP3_MP3Device
{
    TINYCLR_NATIVE_DECLARE(MP3Device_MP3_Initialize___STATIC__VOID);
    TINYCLR_NATIVE_DECLARE(MP3Device_MP3_Play___STATIC__VOID__STRING);
    TINYCLR_NATIVE_DECLARE(MP3Device_MP3_Stop___STATIC__VOID__STRING);
    TINYCLR_NATIVE_DECLARE(MP3Device_MP3_Pause___STATIC__VOID__STRING);
    TINYCLR_NATIVE_DECLARE(MP3Device_MP3_Uninitialize___STATIC__VOID);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_CQ_NETMF_MP3;

#endif  //_CQ_NETMF_MP3_H_
