//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _CQ_NETMF_LCD_H_
#define _CQ_NETMF_LCD_H_

#include <TinyCLR_Interop.h>
struct Library_CQ_NETMF_LCD_CQ_NETMF_LCD_LCDDevice
{
    TINYCLR_NATIVE_DECLARE(LCDDevice_LCD_Initialize___STATIC__VOID);
    TINYCLR_NATIVE_DECLARE(LCDDevice_LCD_Clear___STATIC__VOID);
    TINYCLR_NATIVE_DECLARE(LCDDevice_LCD_BitBltEx___STATIC__VOID__U4__U4__U4__U4__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(LCDDevice_LCD_WriteFormattedChar___STATIC__VOID__U2);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_CQ_NETMF_LCD;

#endif  //_CQ_NETMF_LCD_H_
