//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _CQ_NETMF_SD_H_
#define _CQ_NETMF_SD_H_

#include <TinyCLR_Interop.h>
struct Library_CQ_NETMF_SD_CQ_NETMF_SD_StorageDevice
{
    static const int FIELD_STATIC__SdCardPath = 0;

    TINYCLR_NATIVE_DECLARE(SDSPI_Mount___STATIC__VOID__STRING__U4__U4__U4);
    TINYCLR_NATIVE_DECLARE(SDSPI_Unmount___STATIC__VOID);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_CQ_NETMF_SD;

#endif  //_CQ_NETMF_SD_H_
