//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "CQ_NETMF_UTIL.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    Library_CQ_NETMF_UTIL_CQ_NETMF_UTIL_EEHeap::EEHeap_get_top___STATIC__U4,
    Library_CQ_NETMF_UTIL_CQ_NETMF_UTIL_EEHeap::EEHeap_get_size___STATIC__U4,
    Library_CQ_NETMF_UTIL_CQ_NETMF_UTIL_EEHeap::EEHeap_get_next___STATIC__U4__U4,
    Library_CQ_NETMF_UTIL_CQ_NETMF_UTIL_EEHeap::EEHeap_get_prev___STATIC__U4__U4,
    Library_CQ_NETMF_UTIL_CQ_NETMF_UTIL_EEHeap::EEHeap_get_last___STATIC__U4,
    Library_CQ_NETMF_UTIL_CQ_NETMF_UTIL_EEHeap::EEHeap_get_hb_flags___STATIC__U4__U4,
    Library_CQ_NETMF_UTIL_CQ_NETMF_UTIL_EEHeap::EEHeap_get_hb_size___STATIC__U4__U4,
    Library_CQ_NETMF_UTIL_CQ_NETMF_UTIL_EEHeap::EEHeap_get_hb_type___STATIC__U4__U4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_CQ_NETMF_UTIL =
{
    "CQ_NETMF_UTIL", 
    0xA677597D,
    method_lookup
};

