//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _CQ_NETMF_UTIL_H_
#define _CQ_NETMF_UTIL_H_

#include <TinyCLR_Interop.h>
struct Library_CQ_NETMF_UTIL_CQ_NETMF_UTIL_EEHeap
{
    static const int FIELD_STATIC__m_top = 0;
    static const int FIELD_STATIC__m_size = 1;

    TINYCLR_NATIVE_DECLARE(EEHeap_get_top___STATIC__U4);
    TINYCLR_NATIVE_DECLARE(EEHeap_get_size___STATIC__U4);
    TINYCLR_NATIVE_DECLARE(EEHeap_get_next___STATIC__U4__U4);
    TINYCLR_NATIVE_DECLARE(EEHeap_get_prev___STATIC__U4__U4);
    TINYCLR_NATIVE_DECLARE(EEHeap_get_last___STATIC__U4);
    TINYCLR_NATIVE_DECLARE(EEHeap_get_hb_flags___STATIC__U4__U4);
    TINYCLR_NATIVE_DECLARE(EEHeap_get_hb_size___STATIC__U4__U4);
    TINYCLR_NATIVE_DECLARE(EEHeap_get_hb_type___STATIC__U4__U4);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_CQ_NETMF_UTIL;

#endif  //_CQ_NETMF_UTIL_H_
